pipeline {
    agent any

    environment {
        APP_NAME = "java-be"
        CONTAINER_NAME = "java-be"
        HOST_PORT = "8083"
        CONTAINER_PORT = "8081"

        DATABASE_URL = "jdbc:postgresql://172.17.0.2:5432/mydb?user=admin&password=123456&sslmode=disable"
    }

    stages {

        stage('1. Checkout') {
            steps {
                echo "=== GIAI ĐOẠN 1: Checkout source code ==="

                // Nếu Jenkins job đã cấu hình Pipeline from SCM
                // thì Jenkins sẽ tự checkout.
                checkout scm
            }
        }

        stage('Debug') {
            steps {
                sh '''
                    echo "=== Current directory ==="
                    pwd

                    echo "=== Project files ==="
                    ls -la

                    echo "=== Files ==="
                    find . -maxdepth 2 -type f | sort
                '''
            }
        }

        stage('2. Build') {
            steps {
                echo "=== GIAI ĐOẠN 2: Maven Build ==="

                sh '''
                    chmod +x mvnw
                    ./mvnw clean package -DskipTests
                '''
            }
        }

        stage('3. Test') {
            steps {
                echo "=== GIAI ĐOẠN 3: Running tests ==="

                sh '''
                    chmod +x mvnw
                    ./mvnw test
                '''
            }
        }

        stage('4. Docker Build') {
            steps {
                echo "=== GIAI ĐOẠN 4: Build Docker Image ==="

                sh '''
                    docker build -t ${APP_NAME}:latest .
                '''
            }
        }

        stage('5. Stop Old Container') {
            steps {
                echo "=== GIAI ĐOẠN 5: Stop container cũ ==="

                sh '''
                    docker rm -f ${CONTAINER_NAME} || true
                '''
            }
        }

        stage('6. Deploy') {
            steps {
                echo "=== GIAI ĐOẠN 6: Deploy container mới ==="

                sh '''
                    docker run -d \
                        --name ${CONTAINER_NAME} \
                        -p ${HOST_PORT}:${CONTAINER_PORT} \
                        -e DATABASE_URL="${DATABASE_URL}" \
                        ${APP_NAME}:latest
                '''
            }
        }

        stage('7. Check') {
            steps {
                echo "=== GIAI ĐOẠN 7: Kiểm tra container ==="

                sh '''
                    sleep 5
                    docker ps
                    docker logs --tail 50 ${CONTAINER_NAME}
                '''
            }
        }
    }

    post {
        success {
            echo '🎉 Pipeline chạy THÀNH CÔNG!'
            echo 'Application: http://localhost:8083'
        }

        failure {
            echo '❌ Pipeline bị lỗi!'
        }
    }
}